chore(deps): bump jni from 0.21.1 to 0.22.4 (#30)
Bumps [jni](https://github.com/jni-rs/jni-rs) from 0.21.1 to 0.22.4.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/jni-rs/jni-rs/releases">jni's
releases</a>.</em></p>
<blockquote>
<h2>Release JNI 0.22.4</h2>
<h3>Added</h3>
<ul>
<li><code>JCharSequence</code> bindings for
<code>java.lang.CharSequence</code> (including
<code>AsRef&lt;JCharSequence&gt;</code> +
<code>.as_char_sequence()</code> for <code>JString</code>) (<a
href="https://redirect.github.com/jni-rs/jni-rs/pull/793">#793</a>)</li>
<li><code>bind_java_type</code> supports <code>non_null</code>
qualifier/property for methods and fields to map null references to
<code>Error::NullPtr</code> (<a
href="https://redirect.github.com/jni-rs/jni-rs/pull/795">#795</a>)</li>
<li><code>bind_java_type</code> supports <code>#[cfg()]</code>
attributes on methods and fields, to conditionally compile them based on
features or other cfg conditions (<a
href="https://redirect.github.com/jni-rs/jni-rs/pull/795">#797</a>)</li>
<li><code>JValueOwned::check_null()</code> + <code>::is_null()</code>
methods for ergonomic null checks on owned (returned) values (<a
href="https://redirect.github.com/jni-rs/jni-rs/pull/798">#798</a>)</li>
<li>More readable type accessors for <code>JValueOwned</code>, like
<code>.into_bool()</code> instead of <code>.z()</code>,
<code>.into_object()</code> instead of <code>.l()</code>, etc (<a
href="https://redirect.github.com/jni-rs/jni-rs/pull/798">#798</a>)</li>
</ul>
<h4>Fixed</h4>
<ul>
<li><code>jni_mangle</code> now includes
<code>docs/macros/jni_mangle.md</code> in the crate documentation, so
the macro's documentation is visible on docs.rs and in IDEs (<a
href="https://redirect.github.com/jni-rs/jni-rs/pull/799">#799</a>)</li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/jni-rs/jni-rs/compare/v0.22.3...v0.22.4">https://github.com/jni-rs/jni-rs/compare/v0.22.3...v0.22.4</a></p>
<h2>Release JNI 0.22.3</h2>
<p>No functional change in this release but it fixes the <a
href="https://docs.rs/jni/latest/jni/">docs.rs</a> build by bumping the
<code>simd_cesu8</code> dep to &gt;= 1.1.1 which no longer has an
automatically-enabled &quot;nightly&quot; feature that may affect the
docs.rs build (1.1.x is now also MSRV compatible).</p>
<p><em>Note: Technically we shouldn't need this release (since the
<code>simd_cesu8</code> release alone will have fixed the build issue)
but the other reason for the release is that the crates.io feature for
queuing docs.rs rebuilds is not currently usable in our situation.
docs.rs is currently fighting through a <a
href="https://docs.rs/releases/queue">huge backlog</a> of low-priority
build jobs that will likely to take over a week to clear (we moved about
500 spots in two days, out of ~3k crates queued).</em></p>
<h2>Release JNI 0.22.2</h2>
<p><em><em>Note</em>: although no breaking API change was made in this
release there were some important fixes made, including a few
non-trivial changes to how exceptions are handled and some important
safety / soundness fixes made in the re-exported
<code>jni-macros</code>.</em></p>
<p><em>For these reasons I'm going to <em>again</em> yank the previous
0.22.1 release after this is published, again taking into account that
0.22.1 was itself only released very recently and it should still be
relatively unlikely that anyone has strictly locked in a 0.22.1
dependency.</em></p>
<p><em>Another benefit to yanking 0.22.1 is that it allows me to pin the
<code>jni-macros</code> dependency via <code>=0.22.2</code> in this
release so that in future releases I don't need to be worried that a new
<code>jni-macros</code> release needs to be backwards compatible with
all prior <code>jni</code> releases (so macros can take advantage of new
<code>jni</code> features).</em></p>
<p><em>Hopefully things will be smoother moving forward, now that more
people have been starting to update to 0.22.x and there are more people
testing it.</em></p>
<h3>Added</h3>
<p>Adds bindings for the following <code>java.lang</code> errors /
exceptions (<a
href="https://redirect.github.com/jni-rs/jni-rs/pull/767">#767</a>):</p>
<ul>
<li><code>JArrayIndexOutOfBoundsException</code>
(<code>java.lang.ArrayIndexOutOfBoundsException</code>)</li>
<li><code>JArrayStoreException</code>
(<code>java.lang.ArrayStoreException</code>)</li>
<li><code>JClassCircularityError</code>
(<code>java.lang.ClassCircularityError</code>)</li>
<li><code>JClassFormatError</code>
(<code>java.lang.ClassFormatError</code>)</li>
<li><code>JExceptionInInitializerError</code>
(<code>java.lang.ExceptionInInitializerError</code>)</li>
<li><code>JClassNotFoundException</code>
(<code>java.lang.ClassNotFoundException</code>)</li>
<li><code>JIllegalArgumentException</code>
(<code>java.lang.IllegalArgumentException</code>)</li>
<li><code>JIllegalMonitorStateException</code>
(<code>java.lang.IllegalMonitorStateException</code>)</li>
<li><code>JInstantiationException</code>
(<code>java.lang.InstantiationException</code>)</li>
<li><code>JLinkageError</code>
(<code>java.lang.LinkageError</code>)</li>
<li><code>JNoClassDefFoundError</code>
(<code>java.lang.NoClassDefFoundError</code>)</li>
<li><code>JNoSuchFieldError</code>
(<code>java.lang.NoSuchFieldError</code>)</li>
<li><code>JNoSuchMethodError</code>
(<code>java.lang.NoSuchMethodError</code>)</li>
<li><code>JNumberFormatException</code>
(<code>java.lang.NumberFormatException</code>)</li>
<li><code>JOutOfMemoryError</code>
(<code>java.lang.OutOfMemoryError</code>)</li>
<li><code>JRuntimeException</code>
(<code>java.lang.RuntimeException</code>)</li>
<li><code>JSecurityException</code>
(<code>java.lang.SecurityException</code>)</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/jni-rs/jni-rs/blob/master/CHANGELOG.md">jni's
changelog</a>.</em></p>
<blockquote>
<h2>[0.22.4] — 2026-03-16</h2>
<h3>Added</h3>
<ul>
<li><code>JCharSequence</code> bindings for
<code>java.lang.CharSequence</code> (including
<code>AsRef&lt;JCharSequence&gt;</code> +
<code>.as_char_sequence()</code> for <code>JString</code>) (<a
href="https://redirect.github.com/jni-rs/jni-rs/pull/793">#793</a>)</li>
<li><code>bind_java_type</code> supports <code>non_null</code>
qualifier/property for methods and fields to map null references to
<code>Error::NullPtr</code> (<a
href="https://redirect.github.com/jni-rs/jni-rs/pull/795">#795</a>)</li>
<li><code>bind_java_type</code> supports <code>#[cfg()]</code>
attributes on methods and fields, to conditionally compile them based on
features or other cfg conditions (<a
href="https://redirect.github.com/jni-rs/jni-rs/pull/795">#797</a>)</li>
<li><code>JValueOwned::check_null()</code> + <code>::is_null()</code>
methods for ergonomic null checks on owned (returned) values (<a
href="https://redirect.github.com/jni-rs/jni-rs/pull/798">#798</a>)</li>
<li>More readable type accessors for <code>JValueOwned</code>, like
<code>.into_bool()</code> instead of <code>.z()</code>,
<code>.into_object()</code> instead of <code>.l()</code>, etc (<a
href="https://redirect.github.com/jni-rs/jni-rs/pull/798">#798</a>)</li>
</ul>
<h4>Fixed</h4>
<ul>
<li><code>jni_mangle</code> now includes
<code>docs/macros/jni_mangle.md</code> in the crate documentation, so
the macro's documentation is visible on docs.rs and in IDEs (<a
href="https://redirect.github.com/jni-rs/jni-rs/pull/799">#799</a>)</li>
</ul>
<h2>[0.22.3] — 2026-03-05</h2>
<h4>Fixed</h4>
<ul>
<li>docs.rs build: Bumps <code>simd_cesu8</code> dep to &gt;= 1.1.1
which no longer has an automatically-enabled
&quot;nightly&quot; feature that may affect the docs.rs build (1.1.x is
now also MSRV compatible) (<a
href="https://redirect.github.com/jni-rs/jni-rs/pull/790">#790</a>)</li>
</ul>
<h2>[0.22.2] — 2026-03-01</h2>
<p><em><em>Note</em>: although no breaking API change was made in this
release there were some important fixes
made, including a few non-trivial changes to how exceptions are handled
and some important safety /
soundness fixes made in the re-exported
<code>jni-macros</code>.</em></p>
<p><em>For these reasons I'm going to <em>again</em> yank the previous
0.22.1 release after this is published,
again taking into account that 0.22.1 was itself only released very
recently and it should still be
relatively unlikely that anyone has strictly locked in a 0.22.1
dependency.</em></p>
<p><em>Another benefit to yanking 0.22.1 is that it allows me to pin the
<code>jni-macros</code> dependency via
<code>=0.22.2</code> in this release so that in future releases I don't
need to be worried that a new
<code>jni-macros</code> release needs to be backwards compatible with
all prior <code>jni</code> releases (so macros can
take advantage of new <code>jni</code> features).</em></p>
<p><em>Hopefully things will be smoother moving forward, now that more
people have been starting to update
to 0.22.x and there are more people testing it.</em></p>
<h3>Added</h3>
<p>Adds bindings for the following <code>java.lang</code> errors /
exceptions (<a
href="https://redirect.github.com/jni-rs/jni-rs/pull/767">#767</a>):</p>
<ul>
<li><code>JArrayIndexOutOfBoundsException</code>
(<code>java.lang.ArrayIndexOutOfBoundsException</code>)</li>
<li><code>JArrayStoreException</code>
(<code>java.lang.ArrayStoreException</code>)</li>
<li><code>JClassCircularityError</code>
(<code>java.lang.ClassCircularityError</code>)</li>
<li><code>JClassFormatError</code>
(<code>java.lang.ClassFormatError</code>)</li>
<li><code>JExceptionInInitializerError</code>
(<code>java.lang.ExceptionInInitializerError</code>)</li>
<li><code>JClassNotFoundException</code>
(<code>java.lang.ClassNotFoundException</code>)</li>
<li><code>JIllegalArgumentException</code>
(<code>java.lang.IllegalArgumentException</code>)</li>
<li><code>JIllegalMonitorStateException</code>
(<code>java.lang.IllegalMonitorStateException</code>)</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/jni-rs/jni-rs/commit/5ae9458a4ec44c5318f37ddc7569c1d4ae8a69e7"><code>5ae9458</code></a>
Release jni 0.22.4</li>
<li><a
href="https://github.com/jni-rs/jni-rs/commit/2f954cdf25ad43fd3656fba123fa8c0071b03d72"><code>2f954cd</code></a>
Fix copy&amp;paste error
s/JString::collection/JString::as_char_sequence/</li>
<li><a
href="https://github.com/jni-rs/jni-rs/commit/33045a124105c939d1e2cbdcb5a39e5d868ffa03"><code>33045a1</code></a>
Release jni-macros 0.22.4</li>
<li><a
href="https://github.com/jni-rs/jni-rs/commit/527703e044558c0604ebd1b29ba9f7fa2c6a7d0e"><code>527703e</code></a>
No longer recommend passing <code>&amp;mut Env</code> as the last
argument</li>
<li><a
href="https://github.com/jni-rs/jni-rs/commit/ce7130b10b76aa0dfe54d6951c3416f32c0f18a1"><code>ce7130b</code></a>
Import docs/macros/jni_mangle.md docs for jni_mangle macro</li>
<li><a
href="https://github.com/jni-rs/jni-rs/commit/d80bf234cfa44c716925ea8ce2097b22bbe2e451"><code>d80bf23</code></a>
Add more-ergonomic JValueOwned accessors</li>
<li><a
href="https://github.com/jni-rs/jni-rs/commit/5ffd96a2aeb20b60ade1049c011e75b784d73c2a"><code>5ffd96a</code></a>
bind_java_type: Support #[cfg()] guarded methods/fields</li>
<li><a
href="https://github.com/jni-rs/jni-rs/commit/b498e9f87018eb2821be08984c5288e170d799a0"><code>b498e9f</code></a>
bind_java_type: support non_null methods/fields</li>
<li><a
href="https://github.com/jni-rs/jni-rs/commit/1f74e4b9c65acac8ee331be0be9df05431413fef"><code>1f74e4b</code></a>
Add <code>objects::JCharSequence</code> binding</li>
<li><a
href="https://github.com/jni-rs/jni-rs/commit/25f810ddd7ce8ac3c93c1c8e98eb6e854e8b2a7d"><code>25f810d</code></a>
Release jni 0.22.3</li>
<li>Additional commits viewable in <a
href="https://github.com/jni-rs/jni-rs/compare/v0.21.1...v0.22.4">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=jni&package-manager=cargo&previous-version=0.21.1&new-version=0.22.4)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>